### ISSUE TITLE
cache-s3 needs packages section in stack.yaml file for it to work

### ISSUE THREAD

**Issue by psibi** [fpco/cache-s3#17]
The packages section in `stack.yaml` file is optional and if it isn't present, the following is assumed by default:

```
packages:
- .
```

Reference: https://docs.haskellstack.org/en/stable/yaml_configuration/#packages-and-extra-deps

This caused a error when using cache-s3 in the Azure CI: https://dev.azure.com/commercialhaskell/stack/_build/results?buildId=329

I fixed it in this commit: https://github.com/commercialhaskell/stack/commit/d322e1a82b8bf884592666cda44ed887f75583a7

Assuming the same semantics for `stack.yaml` as Stack would be nice!

**Comment by lehins** [comment]
~`cache-s3` does not concern itself with `stack.yaml` file at all, it invokes `stack` as a subprocess in order to get the relevant info. There is a good chance that there was an older version of `stack` on stack ci. As far as I remember that `packages` field was not always optional.
@psibi could you please confirm if that is indeed the case, so we can close this issue?~

**Comment by lehins** [comment]
@psibi scratch what I said. I totally forgot about it. It does indeed parse the stack file. This ticket is valid.

**Comment by psibi** [comment]
Yeah, the error arises from this line: https://github.com/fpco/cache-s3/blob/97373c9d0a3e5423b97029b32ff426a5fbb176ca/src/Network/AWS/S3/Cache/Stack.hs#L91

**Comment by psibi** [comment]
Thanks for the quick fix!

**Comment by lehins** [comment]
Glad to help :) Thanks for finding this issue. New release should get uploaded to github as soon as CI is finished.
