### ISSUE TITLE
The default upload/download method is much slower than S3 cp

### ISSUE THREAD

**Issue by aledegano** [fpco/cache-s3#20]
Hello and thank you very much for sharing this project: it has been very useful for my team to provide a generic compilation cache in our infrastructure which is AWS based.

We have noted that the uploads/downloads of the caches, done by cache-s3, are much slower than what we would get with a simple `aws s3 cp`, often by almost a factor of 8/10.

Consider the following log, for instance:
```
[cache-s3][Info ][Wed, 27 Feb 2019 15:32:50 UTC]: <cache-s3/#redacted#/master.cache> - Data change detected, caching 1.2 GiB with sha256: 3vxkxF5XYO9vJLo72s8NyLHNJRn0nOk/iHg0TjgZbZo=
[cache-s3][Info ][Wed, 27 Feb 2019 15:32:55 UTC]: Progress: 10%, speed: 25.4 MiB/s
[cache-s3][Info ][Wed, 27 Feb 2019 15:32:59 UTC]: Progress: 20%, speed: 26.3 MiB/s
[cache-s3][Info ][Wed, 27 Feb 2019 15:33:04 UTC]: Progress: 30%, speed: 26.1 MiB/s
[cache-s3][Info ][Wed, 27 Feb 2019 15:33:08 UTC]: Progress: 40%, speed: 26.3 MiB/s
[cache-s3][Info ][Wed, 27 Feb 2019 15:33:13 UTC]: Progress: 50%, speed: 26.2 MiB/s
[cache-s3][Info ][Wed, 27 Feb 2019 15:33:21 UTC]: Progress: 60%, speed: 14.0 MiB/s
[cache-s3][Info ][Wed, 27 Feb 2019 15:33:26 UTC]: Progress: 70%, speed: 25.9 MiB/s
[cache-s3][Info ][Wed, 27 Feb 2019 15:33:30 UTC]: Progress: 80%, speed: 26.2 MiB/s
[cache-s3][Info ][Wed, 27 Feb 2019 15:33:35 UTC]: Progress: 90%, speed: 25.6 MiB/s
[cache-s3][Info ][Wed, 27 Feb 2019 15:33:39 UTC]: Progress: 100%, speed: 27.2 MiB/s
[cache-s3][Info ][Wed, 27 Feb 2019 15:33:43 UTC]: <cache-s3/#redacted#/master.cache> - Finished uploading. Files are cached on S3.
```

As you can see from the timestamp it took 48 seconds to upload ~1200 MB -> ~25MB/s, consistent with the speed of the partial progress.
I've also compiled a list of logs from other builds and the upload and download speeds are very consistent, even across wildly different caches sizes.

However if I log into the machine and do directly a S3 cp, of the same cache file, to the same bucket it's done in ~6 seconds: ~200MB/s!

I suspect that this might be a consequence of our infrastructure fully residing in AWS and thus the method that cache-s3 natively uses to upload and download objects for S3 is not optimized when the speed can be very high.

**A humble suggestion**
Perhaps it could be added to cache-s3 an optional flag to simply use S3 cp when required?
I'd love to do it myself but I really know nothing of Haskell.
Thank you!

**Comment by lehins** [comment]
Thank you for this report, it is a pretty interesting, but unfortunate finding.

`cache-s3` uses AWS API to upload files to S3 bucket, same as what `aws s3 cp` is using I presume, therefore it is surprising that the speed differs so much. It does seem like a bug to me, not sure where exactly, but it is, because a factor x8 is a serious slow down. I'd rather not work around the problem by calling an external aws-cli, instead I'd prefer to fix the root of the problem. I won't be able to give it any attention within next couple of weeks, but I will certainly try to figure it out. Hopefully it is not too urgent for you.

**Comment by aledegano** [comment]
Thank you for your prompt response!
Don't worry take your time. I'm still available to test anything you might need.

**Comment by mbj** [comment]
I can confirm the speed difference between `cache-s3` and "native" `aws s3 cp`. To me its not a big issue as the code path that needs the cache is rarely hit. Still I may have time to investigate. I'd probably start via adding debug logs to see the individual chunk sizes, and hope that simply adjusting them to the values used by `aws s3 cp` will do the trick.

**Comment by lehins** [comment]
@mbj If you'd be willing to investigate that be great, I'd start with this line: https://github.com/fpco/cache-s3/blob/master/src/Network/AWS/S3/Cache/Remote.hs#L164
And this function in particular: [streamUpload](http://hackage.haskell.org/package/amazonka-s3-streaming-0.2.0.5/docs/Network-AWS-S3-StreamingUpload.html#v:streamUpload)

There might be a chance `getProgressReporter` is messing things up, but it's a pretty light conduit so I doubt it affects the speed much, but testing without it wouldn't hurt.

**Comment by mbj** [comment]
@lehins Also we should check if we for some reason create a fresh TLS connection for each multipart chunk (assuming we use the chunked S3 uploads, did not check so far).

**Comment by wagdav** [comment]
Hello,

@aledeganopix4d  and I did some investigations.

We believe that the Python client is faster because it does the upload:
1. In small chunks (8MB by default)
2. Using multiple concurrent connections (10 by default)

We found these parameters here: https://github.com/aws/aws-cli/blob/develop/awscli/customizations/s3/transferconfig.py

I made an attempt to use the [concurrentUpload](https://hackage.haskell.org/package/amazonka-s3-streaming-0.2.0.5/docs/Network-AWS-S3-StreamingUpload.html#v:concurrentUpload) function in cache-s3 instead. I didn't manage to get it working because `concurrentUpload` has a different signature and I don't know conduits that well.

**Comment by lehins** [comment]
@wagdav Thank you for checking it out. The problem with `concurrentUpload` is that progress reporting becomes impossible, but of course it should bring some speed improvements. I did change it the concurrent upload in this branch: [concurrent-upload](https://github.com/fpco/cache-s3/tree/concurrent-upload)

If you'd be willing to give it a try, that be great.

**Comment by wagdav** [comment]
The `tar` step works, but then it crashes on the upload.
```
[cache-s3][Info ][Fri,  1 Mar 2019 15:39:56 UTC]: Caching: ./ccache
[cache-s3][Info ][Fri,  1 Mar 2019 15:40:23 UTC]: <cache-s3/cache-s3-concurrent-upload/test.cache> - No previously stored cache was found.
[cache-s3][Info ][Fri,  1 Mar 2019 15:40:23 UTC]: <cache-s3/cache-s3-concurrent-upload/test.cache> - Data change detected, caching 558.6 MiB with sha256: SSP8NM7lrZD9bhuKeBrGzFCY8V8DA6bpVyUQB6ZKjU4=
cache-s3: /tmp/cache-s3.tar27485-0.gzip: openBinaryFile: resource busy (file is locked)
```

**Comment by lehins** [comment]
@wagdav Dammit, you gotta close the handle for it to work, try now.
I don't have an S3 bucket deployed right now that I could try it on, otherwise I'd give it a shot myself.

**Comment by wagdav** [comment]
Cool! I made some preliminary tests by uploading a ~500MB  file

* Python client: _only the upload_ takes about 22s
* cache-s3 master branch: takes about 30s compressing and 70s uploading (total 100s )
* cache-s3 concurrent-upload branch: 30s compressing and 22s upload (total 52s)

These were just individual runs with the `time` command in the console, but it seems that in the `concurrent-upload` branch the upload speed is in par with the official client!

**Comment by rvl** [comment]
Hi, we also see slowness when downloading caches. It's about 1.3MiB/s. 
As far as I can tell, multipart parallel downloads are not implemented in amazonka-s3.

**Comment by lehins** [comment]
Just made a [new release](https://github.com/fpco/cache-s3/releases/tag/v0.1.8) that includes concurrent uploads, so pushing cache upstream now will be fast. Unfortunately with downloads it isn't that simple. There seems to be no one-line solution for this. But it is not impossible. It looks like there is a way to download chunks concurrently from S3 with amazonka, all that is left is the implementation of concurrent downloading and then sequential recombining of those chunks ;) I do have some ideas, but can't make any promises, since I don't think any of our clients are in need of this feature.  I do like the problem, so I might tackle it my spare time.

**Comment by aledegano** [comment]
That's good news, thank you @lehins! I'll come back to you as soon as we'll have time to test it.

**Comment by wagdav** [comment]
On behalf of @aledeganopix4d : we're very happy with the upload performance! We're running `v0.1.9` now in production! Thanks!
